mp4: move techsmith fork detection to configure
Add a block to the configuration script that seems to adequately detect
for the techsmith fork. Basically, if we can't detect the header but
can still confirm that the library exists through try_link, we just
assume it's the techsmith fork since by default the busted header
won't compile.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -406,17 +406,50 @@ check_roar()
 	return $?
 }
 
+ts_mp4v2_code="
+#include <mp4v2/mp4v2.h>
+
+int main() { 
+	MP4Read("/dev/null"); 
+	return 0; 
+}
+"
+
 check_mp4()
 {
 	USE_MPEG4IP=1
+	IS_TS_MP4V2=0
+
 	if check_header mp4v2/mp4v2.h
 	then
 		USE_MPEG4IP=0
 	else
-		check_header mp4.h || return $?
+		# make sure that mp4v2 isn't hiding under an mp4.h header
+		if check_header mp4.h
+		then
+			USE_MPEG4IP=1
+		else
+			# techsmith cripples the mp4v2 api so badly that we can't even check for
+			# headers, as the C++ causes any call to gcc to just fail. If the header
+			# check fails but mp4v2 is still linkable, assume that we the system has
+			# the techsmith fork and mark it as such.
+			msg_checking "for techsmith mp4v2 fork"
+
+			if try_link -lmp4v2
+			then
+				msg_result yes
+				USE_MPEG4IP=0
+				IS_TS_MP4V2=1
+			else
+				msg_result no
+				return $?
+			fi
+		fi
 	fi
+
 	check_header neaacdec.h &&
 	check_library MP4 "" "-lmp4v2 -lfaad -lm"
+
 	return $?
 }
 
@@ -597,7 +630,7 @@ check check_jack       CONFIG_JACK
 check check_samplerate CONFIG_SAMPLERATE
 check check_ao         CONFIG_AO
 check check_coreaudio  CONFIG_COREAUDIO
-check check_arts       CONFIG_ARTS
+check check_arts       CONFIG_ARTST
 check check_oss        CONFIG_OSS
 check check_sndio      CONFIG_SNDIO
 check check_sun        CONFIG_SUN
@@ -626,7 +659,7 @@ config_header config/debug.h DEBUG
 config_header config/tremor.h CONFIG_TREMOR
 config_header config/modplug.h MODPLUG_API_8
 config_header config/mpc.h MPC_SV8
-config_header config/mp4.h USE_MPEG4IP
+config_header config/mp4.h USE_MPEG4IP IS_TS_MP4V2
 config_header config/curses.h HAVE_RESIZETERM HAVE_USE_DEFAULT_COLORS
 config_header config/ffmpeg.h HAVE_FFMPEG_AVCODEC_H USE_FALLBACK_IP
 config_header config/utils.h HAVE_BYTESWAP_H
