desperate ci fix 4

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -415,7 +415,20 @@ check_mp4()
 	then
 		USE_MPEG4IP=0
 	else
-		return $?
+		# techsmith cripples the mp4v2 api so badly that we can't even check for
+		# headers, as the C++ causes any call to gcc to just fail. If the header
+		# check fails but mp4v2 is still linkable, assume that we the system has
+		# the techsmith fork and mark it as such.
+		msg_checking "for techsmith mp4v2 fork"
+
+		if try_link -lmp4v2
+		then
+			msg_result yes
+			return $?
+		else
+			msg_result no
+			return $?
+		fi
 	fi
 
 	check_header neaacdec.h &&
